### ISSUE TITLE
Question about rules

### ISSUE THREAD

**Issue by hpapagaj** [Erikvl87/docker-languagetool#11]
I have set up and running LanguageTool in Docker, it works great.

One thing I am not sure about, I found out that some rules are disabled by default, [example](https://community.languagetool.org/rule/show/MUZSKY_ROD?lang=sk&subId=4). It is somehow possible to enable these rules, or they require premium subscription?

**Comment by Erikvl87** [comment]
Hi @hpapagaj, your question seems not related to the Docker setup so the appropriate place to ask this would be in the [official LanguageTool repository](https://github.com/languagetool-org/languagetool) or it's [forum](https://forum.languagetool.org/).

Nevertheless I think this is what you are looking for. Try the request as follows:
- Go to https://languagetool.org/http-api/swagger-ui/#!/default/post_check
- Set the following request parameters:
-- `language` to `sk`
-- `enabledRules` to `MUZSKY_ROD` (note that you can find this rule identifier on the rule page you referred to)
-- `enabledOnly` to `true`
- Press the `Try it out!` button
- Inspect the `Response Body` to see if matches are returned related to the given rule.

Can you confirm that your question is not related to the Docker setup so I can close this issue?

**Comment by hpapagaj** [comment]
I fixed it by login into Docker container as root and edit ./org/languagetools/rules/sk/grammar.xml and here remove default="off" from rules I want to enable.

**Comment by Erikvl87** [comment]
Thank you for posting your solution!
