### ISSUE TITLE
Support for docker USER UID PID needed

### ISSUE THREAD

**Issue by travelg** [Erikvl87/docker-languagetool#19]
Please include  support for run this image as specific docker user. As running as root is not identical. Thanks.

**Comment by Erikvl87** [comment]
Could you explain in more detail what you are requesting? The Dockerfile already contains [an instruction to use a non-root user](https://docs.docker.com/engine/reference/builder/#user) when running the image. See this commit: https://github.com/Erikvl87/docker-languagetool/commit/f02abaf6a690dcc4037eb2269d517c7c416f3ef8
