### ISSUE TITLE
run on 0.0.0.0

### ISSUE THREAD

**Issue by yondu22** [Erikvl87/docker-languagetool#2]
I need to run it on 0.0.0.0 to allow external connections to the docker, i tried this
docker run --rm -p 8010:8010 --env langtool_setServerURL="0.0.0.0" erikvl87/languagetool

but it still started the server on localhost, which is 127.0.0.1 and that is only for internal machine ip.

Could you help

**Comment by Erikvl87** [comment]
The setting `setServerURL` refers to the listening IP within the image. You do not need to change that.

By default, Docker should already be listening to IP `0.0.0.0`. It will forward `0.0.0.0:8010` on your host machine to the image by using a mapping.

You could verify that by running the image and in another shell execute `docker ps`. You should see something like this:

```
CONTAINER ID        IMAGE                   COMMAND             CREATED             STATUS              PORTS                    NAMES
e4d5c954d9d8        erikvl87/languagetool   "bash start.sh"     45 seconds ago      Up 44 seconds       0.0.0.0:8010->8010/tcp   charming_jang
```

Notice the `0.0.0.0:8010->8010/tcp`.

If it shows you something else, you could try to explicitly set the listening IP:
`docker run --rm -p 0.0.0.0:8010:8010 erikvl87/languagetool`

https://docs.docker.com/v17.12/edge/engine/reference/commandline/run/#publish-or-expose-port--p-expose

**Comment by Erikvl87** [comment]
Regardless of your issue you did bring an error in the Dockerfile to my attention that I will fix, which is causing permission errors when passing in languagetool settings using the `langtool` prefix. I've created bug #3 for that.

**Comment by yondu22** [comment]
I have the same results as you
```
8dd5474203da        erikvl87/languagetool   "bash start.sh"          11 minutes ago      Up 11 minutes       0.0.0.0:8010->8010/tcp           great_jones
```

How every doing this on a machine on the same intranet 
```
curl --data "language=en-US&text=a simple test" http://192.168.0.35:8081/v2/check
curl: (7) Failed to connect to 192.168.0.35 port 8081: Operation timed out
```

or doing this on the same machine
```
curl --data "language=en-US&text=a simple test" http://localhost:8081/v2/check
curl: (7) Failed to connect to localhost port 8081: Connection refused
```

I have gotten many other dockers to work with post request, but not sure what I am doing wrong with this

**Comment by yondu22** [comment]
I have simspell docker running and it works with post requests, here is how docker ps looks
```
CONTAINER ID        IMAGE                   COMMAND                  CREATED             STATUS              PORTS                            NAMES
8dd5474203da        erikvl87/languagetool   "bash start.sh"          15 minutes ago      Up 15 minutes       0.0.0.0:8010->8010/tcp           great_jones
9c37a4357574        symspellapi             "dotnet SymSpellAPI.…"   45 minutes ago      Up 44 minutes       5000/tcp, 0.0.0.0:5000->80/tcp   trusting_moser
```

**Comment by Erikvl87** [comment]
Your `curl` command refers to port `8081` while the Docker instance is listening on `8010`. Could you try port `8010` instead?

**Comment by yondu22** [comment]
sorry I didn't even notice that I just thought it was the same port
thank you
```
 curl --data "language=en-US&text=a simple test" http://192.168.0.35:8
010/v2/check
{"software":{"name":"LanguageTool","version":"4.8","buildDate":"2019-12-28 14:21","apiVersion":1,"premium":false,"premiumHint":"You might be missing errors only the Premium version can find. Contact us at support<at>languagetoolplus.com.","status":""},"warnings":{"incompleteResults":false},"language":{"name":"English (US)","code":"en-US","detectedLanguage":{"name":"French","code":"fr","confidence":0.815771}},"matches":[{"message":"This sentence does not start with an uppercase letter","shortMessage":"","replacements":[{"value":"A"}],"offset":0,"length":1,"context":{"text":"a simple test","offset":0,"length":1},"sentence":"a simple test","type":{"typeName":"Other"},"rule":{"id":"UPPERCASE_SENTENCE_START","description":"Checks that a sentence starts with an uppercase letter","issueType":"typographical","category":{"id":"CASING","name":"Capitalization"}},"ignoreForIncompleteSentence":true,"contextForSureMatch":-1}]}
```

**Comment by Erikvl87** [comment]
Yeah I've thought of changing it to the default port but that would be breaking current implementations. Nevertheless, good to hear you got it working!

I will keep this issue open until I've added a remark in the README.md that explains the endpoint to use.

**Comment by yondu22** [comment]
ya if you can just add this to the readme as a test
```
curl --data "language=en-US&text=a simple test" http://localhost:8010/v2/check
```

**Comment by Erikvl87** [comment]
I've updated the instructions. Thanks @yondu22
