### ISSUE TITLE
Is this project free and open-source?

### ISSUE THREAD

**Issue by NickKaramoff** [Erikvl87/docker-languagetool#20]
This project doesn't have any licence file attached to it. This makes the source code fall under your exclusive copyright, which means that others aren't really allowed to freely use, modify, or share this [(source)](https://choosealicense.com/no-permission/).

Was this your intention? If not, please add an open-source licence file to this repo. I suggest [GNU LGPLv3](https://choosealicense.com/licenses/lgpl-3.0/) to somewhat mirror the licence of LanguageTool itself (which is the compatible LGPLv2.1), but you're free to choose since you, as far as I unserstand, aren't reusing any code from them.

**Comment by Erikvl87** [comment]
Thank you for pointing that out! The project is free to use, modify or share. I'll soon be adding a license file to reflect that.

**Comment by Erikvl87** [comment]
Hey @NickKaramoff , you seem to have some knowledge on this subject. Why would I use the  GNU LGPLv3 license over the MIT license, for example? Would the only argument be to stay close to the license of LanguageTool itself (which may be a very good reason)? It seems to me that LGPLv3 has some more stricter conditions to those that want to bundle this with their own software.

**Comment by NickKaramoff** [comment]
Well, like they say, there are two types of people 😄

For some, it is important that the project is easy to modify and reuse, and they don't want to restrict others. For situations like this, MIT is a good licence. I personally like BSD-3-Clause more, because there is this additional clause about other not being able to use your name for promoting the modification.

For others, it's important that all the improvements are also open-source. This is where (A/L)GPL comes in. It also allows everyone to do everything, but it requires others to publish their **modifications** (not usage) under the same licence. This way, improvements to FOSS stay open-source.

When it comes to this project, I don't _really_ see the need to use any of the GPL licences. While being good, I don't like them for their restrictions and bulkiness. However, if you use code from LanguageTool repo (for example, one could argue you took parts from `build.sh`), then you're obliged to use LGPL. Moreover, I have just read LGPL-2.1 and from what I understand, you **can't** use LGPLv3, but only 2.1, as stated in p. 2c) of [the Terms](https://www.gnu.org/licenses/old-licenses/lgpl-2.1#SEC3).

**Comment by py-crash** [comment]
Hi! The problem is that when no License is specified, it should be taken as All rights reserved, making for example my contribution to the project null and void. Also my [LibreGrammar image](https://github.com/py-crash/libregrammar). The legal side, it's usually not something that we like to take care about, but it's necesary.

**Comment by py-crash** [comment]
Basically you have two types of Licences:
* Those one with COPYLEFT. E.g., LGPL, GPL, AGPL. Those make it mandatory to redistribute changes with the same license or a compatible one. For example, as stated by @NickKaramoff, if you used some code from LanguageTool you MUST use LGPL, or a compatible one, such as GPL.
* Those who don't have copyleft. E.g., MIT Licence. With these licences you can keep your changes and create a proprietary product. 

The only difference with LGPL and GPL  is the ability to be linked with other proprietary bits. An LGPL project could be linked with proprietary programs (for example a proprietary docker/container runtime), a GPL one could not. That's the reason why LPGL could be a good Licence for this project (and also near to upstream).

**Comment by Erikvl87** [comment]
Thank you for educating me on this subject 😉. I have the following PR ready which would add the LPGL 2.1 license to this project. Would merging PR #24 solve your concerns?

**Comment by NickKaramoff** [comment]
Yup, looks good to me! :+1: I would get rid of the extension though, since it's technically not a Markdown file. Make it `LICENSE.txt` or simply `LICENSE`
