### ISSUE TITLE
proper ngrams mounting?

### ISSUE THREAD

**Issue by gerroon** [Erikvl87/docker-languagetool#22]
Hi

Are we mounting the zip file, or unzip folder or "en" (for english) inside the zip folder, or the sub [1,2,3]grams folder inside that?

thanks

**Comment by Erikvl87** [comment]
You should unzip the file first and point to the parent folder of the "en" folder.
Take the following folder structure as an example:
```
my/
├─ ngrams/
│  ├─ en/
│  ├─ nl/
```

You would have to point to `my/ngrams`, thus the startup command would be:
`docker run --rm -it -p 8010:8010 -e langtool_languageModel=/ngrams -v my/ngrams:/ngrams erikvl87/languagetool`

Does this answer your question?

I will clarify this in the README.md file.

**Comment by gerroon** [comment]
Thanks yes veru helpful

**Comment by Erikvl87** [comment]
Great! I've updated the README.md to clarify this for others as well.
