### ISSUE TITLE
Automatic POST every 30s

### ISSUE THREAD

**Issue by ma-ludw** [Erikvl87/docker-languagetool#45]
If I run the docker image, it does an automatic POST request every 30s.
I want to run the image on my Synology NAS and these POST request prevents the hard disks to go in hibernation state. I tried the image on my Windows machine with the same outcome.

If I run the LanguageTool server without the docker image on my Windows machine with java, there are no requests sent.

![Screenshot 2022-06-25 134406](https://user-images.githubusercontent.com/68691403/175773205-b1700891-a615-48e7-af19-1504cb91e3dc.png)

**Comment by Erikvl87** [comment]
Hi @ma-ludw, those are the `HEALTHCHECK` requests. You can consider disabling those by adding the `--no-healthcheck` argument to the startup / `docker run` command.

Source: https://docs.docker.com/engine/reference/run/#healthcheck

**Comment by ma-ludw** [comment]
This solves the problem. Now I have to figure out how I can pass the argument to the container on my synology nas GUI. In the cli it works without any problems.
Thank you.

Maybe it would be nice to add this information to the README.
