### ISSUE TITLE
Container is not receiving Ctrl-C signals

### ISSUE THREAD

**Issue by rsmith31415** [Erikvl87/docker-languagetool#49]
First of all, thank you for providing this Dockerfile. The app in the container is working well, however, it is not receiving signals (in particular, Ctrl-C is ignored), so it is not possible to shutdown the container. As a workaround, it is necessary to run `docker stop <name>` , which is not so convenient. 

I was wondering if it is possible to change the way in which languagetool is launched so that the server can be shutdown gracefully after pressing Ctrl-C. I tried well-known approaches (e.g. adding `--init` to the `docker run` command or building the image using Tini), however, `docker build .` throws warnings for Illegal reflective access.

Just in case it is relevant, I'm following the most straightforward instructions on Ubuntu 22.04.1:

```
docker pull erikvl87/languagetool
docker run --rm -p 8010:8010 erikvl87/languagetool
```

Thanks

**Comment by Erikvl87** [comment]
Hi @rsmith31415,

Could you try running the image using the following command instead?
`docker run --rm -it -p 8010:8010 languagetool`

Adding `-it` will run it as an interactive process. See the following Docker documentation link for more information.
https://docs.docker.com/engine/reference/run/#foreground

Please let me know if this is what you were looking for, so we can close the issue.

**Comment by rsmith31415** [comment]
That certainly "fixes" it. I think I confused myself because the other snippets in the README.md run it interactively and only the first one doesn't. I apologize for the noise here. 

Thanks!

**Comment by Erikvl87** [comment]
Glad it worked! You're welcome!
