### ISSUE TITLE
Access to premium account

### ISSUE THREAD

**Issue by SophieMBerger** [Erikvl87/docker-languagetool#87]
When running this Docker image on a remote Ubuntu instance server I see the following error:

`Error: org.languagetool.server.AuthException: This is the endpoint for the basic version of LanguageTool. When using 'username' and 'apiKey' to access the premium version, use api.languagetoolplus.com instead`

Does this Docker image support premium accounts?

**Comment by Erikvl87** [comment]
Hi @SophieMBerger, unfortunately the premium version is only available in the cloud.

https://github.com/languagetool-org/languagetool/issues/5591#issuecomment-907858568
